spring.application.name=Spring-Boot-First-Application

# Example2 (DatabaseConfiguration)

db.port=3306
db.url=localhost1234
db.username=Tushar
db.password=23896


# Example2 (EmailCredentialConfiguration)

spring.mail.host=smtp.gmail.com
#spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


# Example3 (OrganizationInfo)

org.emp.count=100

org.dept.Names=HR,MANAGER,ADMIN





